name: Build and Deploy NestJS App
run-name: ${{ github.actor }} is Build and Deploy NestJS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: |
          echo "ENV variable ${{ env.NODE_ENV  }}"
          echo "ENV secret ${{ env.NODE_SECRET  }}"
          echo "Deploy ${{ GITHUB_SHA  }}"
