name: Build and Deploy NestJS App
run-name: ${{ github.actor }} is Build and Deploy NestJS App

on:
  push:
    branches: [main, develop]

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      env_input: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    secrets:
      node_secret: ${{ secrets.NODE_SECRET }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    # cannot set environment: ${{ ENVIRONMENT }}
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v3
        # - name: Install dependencies
        #   run: npm install
        # - name: Build the app
        #   run: npm run build
      - name: Build
        run: |
          echo "ENVIRONMENT is ${{ env.ENVIRONMENT }}!"
          echo "ENV variable ${{ vars.NODE_ENV  }}"
          echo "ENV secret ${{ secrets.NODE_SECRET  }}"
          echo "Build... $GITHUB_SHA"

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    # cannot set environment: ${{ ENVIRONMENT }}
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: npm install
      - name: Deploy
        run: |
          echo "ENVIRONMENT is ${{ env.ENVIRONMENT }}!"
          echo "ENV variable ${{ vars.NODE_ENV  }}"
          echo "ENV secret ${{ secrets.NODE_SECRET  }}"
          echo "Deploy... $GITHUB_SHA"
