on:
  workflow_call:
    inputs:
      env_input:
        required: true
        type: string
    secrets:
      NODE_SECRET:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "token is ${{ secrets.NODE_SECRET }}!"
          echo "env_input is ${{ inputs.env_input }}!"
